### PR TITLE
Interpretations & Edits 

### LINKED ISSUE #5: Interpretation

### PR DESCRIPTION
**Pull request by nicolebid**
Hi team, I started editing the `Airbnb_analysis.ipynb` file. I made edits up to the Preprocessing and Transformation section and will continue on later today. Feel free to review/edit as you wish.

### CODE REVIEW

**Comment by nicolebid** [comment]
update: I did edits up to the interpretation & feature importance section.

**Comment by nicolebid** [comment]
Update: Just the conclusion is left to do! :)

**Comment by nicolebid** [comment]
I updated the code (adjusting the engineered features and doing a log transformation on price) and some of the written parts up to the feature selection section, the rest hasn't been updated yet. Feel free to merge this to main and make any adjustments you see fit. :)

**Review by MoNorouzi23 — APPROVED** [review]
Great!

**Pull request merged**
